project:
  type: website

website:
  title: "Encuesta de encuestas"
  navbar:
    left:
      - text: Inicio
        href: index.qmd
      - text: Voto total
        href: "#gr치ficos-de-votos-totales"
      - text: Voto v치lido
        href: "#gr치ficos-de-votos-v치lidos"
    right:
      - icon: github
        href: https://github.com/hescalar/encuesta_encuestas_bol25

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    fig-align: center
    fig-width: 9
    fig-height: 5
    fig-responsive: true
    css: styles.css